String        m_ssid = "Blinky-Lite";
String        m_wifiPassword = "xxx";
String        m_mqttServer  = "192.168.0.101";
String        m_mqttUsername = "blinky-lite-box-01";
String        m_mqttPassword = "xxx";
String        m_mqttPublishTopic;
String        m_mqttSubscribeTopic;
String        m_box = "blinky-lite-box-01";
String        m_trayType = "lora-gateway";
String        m_trayName = "10";
String        m_cubeType = "cube";
